/*
 * PrOOPt — Object-Oriented Prompt Engineering for Java.
 *
 * Copyright (c) 2026 Akshay Rawal
 * SPDX-License-Identifier: MIT
 *
 * Licensed under the MIT License. See the LICENSE file in the project root.
 */
package io.github.argonizer.prooopt.dynamic;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import io.github.argonizer.prooopt.model.ModelTier;

/**
 * A prompt function generated at runtime by the orchestrator LLM when no registered tool satisfies a
 * discovered capability gap.
 *
 * <p>Dynamic functions:
 * <ul>
 *   <li>Always return {@link String} (no Java type info is available at generation time)</li>
 *   <li>Are session-scoped — discarded when {@code PrOOPtContext.clear()} is called</li>
 *   <li>Participate in execution plans, audit logging, and autoboxing exactly like statically
 *       declared {@code @PromptFunction} methods</li>
 *   <li>Are capped per run by {@code maxDynamicFunctions} on {@code @PromptOrchestrator}</li>
 * </ul>
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record DynamicPromptFunction(
        String name,           // camelCase, generated by LLM
        String prompt,         // template with {paramName} placeholders
        ModelTier model,       // tier recommended by the generating LLM
        String description,    // one-sentence description
        String traceId,        // traceId of the run that generated it
        long generatedAtMs     // epoch millis
) {

    /** Dynamic functions always produce String output — safe, unambiguous. */
    public Class<?> returnType() {
        return String.class;
    }
}
