/*
 * PrOOPt — Object-Oriented Prompt Engineering for Java.
 *
 * Copyright (c) 2026 Akshay Rawal
 * SPDX-License-Identifier: MIT
 *
 * Licensed under the MIT License. See the LICENSE file in the project root.
 */
package io.github.argonizer.prooopt.apt;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Builds the Java source of a generated {@code <Interface>PromptDescriptor} class from the captured
 * per-method generic shapes. Pure string assembly so it is unit-testable without a {@code Filer}.
 */
public final class DescriptorWriter {

    /** One captured method: name + raw container type + ordered type-argument FQNs. */
    public record Entry(String methodName, String rawTypeFqn, List<String> typeArgFqns) {
    }

    private DescriptorWriter() {
    }

    /** The generated class's simple name for a given annotated type. */
    public static String descriptorSimpleName(String enclosingSimpleName) {
        return enclosingSimpleName + "PromptDescriptor";
    }

    /** Renders the full source for {@code <enclosingSimpleName>PromptDescriptor} in {@code packageName}. */
    public static String write(String packageName, String enclosingSimpleName, List<Entry> entries) {
        String className = descriptorSimpleName(enclosingSimpleName);
        StringBuilder sb = new StringBuilder();
        if (packageName != null && !packageName.isEmpty()) {
            sb.append("package ").append(packageName).append(";\n\n");
        }
        sb.append("import io.github.argonizer.prooopt.descriptor.PromptMethodDescriptor;\n");
        sb.append("import java.util.List;\n\n");
        sb.append("// Generated by prooopt-apt — do not edit.\n");
        sb.append("public final class ").append(className).append(" {\n\n");
        sb.append("    private ").append(className).append("() {\n    }\n\n");

        Set<String> usedConstants = new HashSet<>();
        for (Entry e : entries) {
            String constant = uniqueConstant(constantName(e.methodName()), usedConstants);
            sb.append("    public static final PromptMethodDescriptor ").append(constant)
                    .append(" = PromptMethodDescriptor.of(\n");
            sb.append("            \"").append(e.methodName()).append("\",\n");
            sb.append("            \"").append(e.rawTypeFqn()).append("\",\n");
            sb.append("            ").append(typeArgsLiteral(e.typeArgFqns())).append(");\n\n");
        }
        sb.append("}\n");
        return sb.toString();
    }

    private static String typeArgsLiteral(List<String> args) {
        if (args == null || args.isEmpty()) {
            return "List.of()";
        }
        List<String> quoted = new ArrayList<>();
        for (String a : args) {
            quoted.add("\"" + a + "\"");
        }
        return "List.of(" + String.join(", ", quoted) + ")";
    }

    /** {@code getLanguages} → {@code GET_LANGUAGES}; {@code toURL} → {@code TO_U_R_L}-safe upper snake. */
    static String constantName(String methodName) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < methodName.length(); i++) {
            char c = methodName.charAt(i);
            if (Character.isUpperCase(c) && i > 0) {
                sb.append('_');
            }
            sb.append(Character.toUpperCase(c));
        }
        return sb.toString();
    }

    private static String uniqueConstant(String base, Set<String> used) {
        String name = base;
        int n = 2;
        while (!used.add(name)) {
            name = base + "_" + n++;
        }
        return name;
    }
}
